sudo: required
services:
  - docker
script:
  - make windows
before_deploy:
  - echo -e "machine github.com\nlogin galeksandrp\npassword $GITHUB_TOKEN" >> ~/.netrc
  - git tag -f $(git describe --always)-$TRAVIS_BRANCH-deploy
  - git push origin -f $(git describe --always)-$TRAVIS_BRANCH-deploy
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file: 
  - dist/*
  file_glob: true
  overwrite: true
  on:
    all_branches: true
branches:
  except:
    - /^deploy-.*$/
    - /^.*-deploy$/
    - /^untagged-.*$/
notifications:
  email: false
